project:
  type: website
  output-dir: docs

website:
  description: "Website about the Misinformation Effect Replication Project"
  site-url: https://misinforep.github.io
  title: "Misinformation Effect Replication Project"
  navbar:
    right:
      - blog.qmd
      - collab.qmd
      - icon: github
        href: https://github.com/misinforep
      # - icon: bluesky
      #   href: https://bsky.app/
format:
  html:
    theme:
      - spacelab
      - brand
    css: styles.css
    primary: '#006699'
    mainfont: "Open Sans"
    monofont: "Fira Code"



